### ISSUE TITLE
Cannot find module 'router/engine' error when running with osprey

### ISSUE THREAD

**Issue by jewelsjacobs** [mulesoft-labs/osprey-router#1]
I was running `osprey@0.2.0-alpha node_modules/osprey` with `"express": "^4.12.0"` on the latest version of `nodeJS (v0.12.0)`.

https://github.com/jewelsjacobs/raml-osprey-api-designer/blob/master/routes/documentation.js#L85

I think this might be caused by a bug in https://github.com/pillarjs/router which references a path that does not resolve to a file or module.  I went ahead and logged an issue in that repo: https://github.com/pillarjs/router/issues/16

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'router/engine'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jewelsjacobs/WebstormProjects/raml-api-designer/node_modules/osprey/node_modules/osprey-router/osprey-router.js:1:76)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by blakeembrey** [comment]
Patched in `router`.
